### ISSUE TITLE
Is this magazine still updating?

### ISSUE THREAD

**Issue by jerryshell** [zineland/2d2d#16]
Hello.
I've been subscribing to TO-D 's RSS for a long time.
I've been cleaning up my RSS Feeds recently.
I found that TO-D 's last article was almost a year ago.
So I want to ask if TO-D is still updating?
Your article is very wonderful. I like your article.
Thanks for your reading. Have a best day.

**Comment by Folyd** [comment]
Hi, @jerryshell. Glad you like TO-D magazine. I don't have much time to update the magazine in the recent future. Sorry.

**Comment by jerryshell** [comment]
Thanks for your excellent work. I will keep TO-D in my RSS Feeds.
